### ISSUE TITLE
AUTH - AWS integration

### ISSUE THREAD

**Issue by Noabsa** [nabsa-me/spotmefy#1]
**Tasks**
- [ ] Delete Express layer and implement AWS Rest Api with Lambdas
     - auth /  login
     - auth /  logout
     - auth /  refresh
    
- [ ] Delete REQUEST and implement AXIOS
- [ ] Complete all success and error cases in lambdas
- [ ] Authorization & roles for Lambdas & API
- [ ] Extra case for save token (log and refresh only when is needed)
- [ ] Add security layer with AUTHORIZATION CODE WITH PKCE EXTENSION
- [ ] Typescript implementation

**Debug environment**
- [ ] Create event files
- [ ] Create config .launcher

**Jest**
- [ ] Create Jest tests
- [ ] Dig into sanitizer tests and automation tests

**JSDocs documentation**
- [ ] Stacks, resources, functions and interfaces documented

**README.md**
- [ ] Description of the module
- [ ] Workflows explained
