### ISSUE TITLE
GENERAL - Observability

### ISSUE THREAD

**Issue by Noabsa** [nabsa-me/spotmefy#2]
**Tasks**
- [ ] Specific lambda for log errors
- [ ] Lambda for log workflows, project observability
- [ ] Event bridge integration

**Debug environment**
- [ ] Create event files
- [ ] Create config .launcher

**Jest**
- [ ] Create Jest tests
- [ ] Dig into sanitizer tests and automation tests

**JSDocs documentation**
- [ ] Stacks, resources, functions and interfaces documented

**README.md**
- [ ] Description of the module
- [ ] Sources links
